### PR TITLE
feat: Add custom tags option to mig-vm-module

### PR DESCRIPTION
**Pull request by ChaosCypher**
- Allows additional tags to be added to the mig-vm-module

### CODE REVIEW

**Comment by nesbittryan** [comment]
Wow! We need this in our project ASAP 🙏 👍

**Comment by nesbittryan** [comment]
The new title is so accurate 🥇 I **knew** this would be a **feat**

**Comment by ChaosCypher** [comment]
@apeabody - I'm unable to see what failed in the terraform-google-github-actions-runners-int-trigger job

**Comment by apeabody** [comment]
> @apeabody - I'm unable to see what failed in the terraform-google-github-actions-runners-int-trigger job

I'm not convinced this is related to your change, I'm going to trigger a fresh run:

```
TestGhRunnerGkeDindRootless 2024-08-16T21:26:05Z command.go:100: Running command gcloud with args [container clusters get-credentials gh-runner-dind-rootless --location us-east4-a --project ci-terraform-gh-runners-1853 --format json]
TestGhRunnerGkeDindRootless 2024-08-16T21:26:07Z command.go:185: Fetching cluster endpoint and auth data.
TestGhRunnerGkeDindRootless 2024-08-16T21:26:08Z command.go:185: kubeconfig entry generated for gh-runner-dind-rootless.
TestGhRunnerGkeDindRootless 2024-08-16T21:26:08Z command.go:185: []
TestGhRunnerGkeDindRootless 2024-08-16T21:26:08Z logger.go:66: Running command kubectl with args [get pods -n arc-systems -o json]
TestGhRunnerGkeDindRootless 2024-08-16T21:26:08Z logger.go:66: error: error loading config file "/builder/home/.kube/config": yaml: line 25: could not find expected ':'
    gh_runner_gke_dind_rootless_test.go:57: Error getting pods: error while running command: exit status 1; error: error loading config file "/builder/home/.kube/config": yaml: line 25: could not find expected ':'
```

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @ChaosCypher!

**Pull request merged**
