### PR TITLE
feat: Add pre post gh runner setup script

### PR DESCRIPTION
**Pull request by kvanzuijlen**
- Added variables to run custom commands before and after the default (provided) startup script

This is useful for (among others) actions that don't use docker to pull the required image. An example is [FairwindsOps/pluto](https://github.com/FairwindsOps/pluto). Their action uses podman instead.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@kvanzuijlen
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @kvanzuijlen 
For the pre/post, I am leaning towards not adding them as a custom script can be supplied via `var.startup_script`.

**Comment by kvanzuijlen** [comment]
I agree that the provided solution is a bit fishy, reason for me was that I don't want to manage the full startup script myself and instead use as much of the provided startup script (without copying it to automatically stay up to date with changes). Maybe we can come up with an alternative for this situation?

**Comment by kvanzuijlen** [comment]
@bharathkkb Maybe we could make use of [cloudinit](https://registry.terraform.io/providers/hashicorp/cloudinit/latest/docs) (move the default script to cloudinit and make the startup script user-provided, or the other way around)?

**Pull request closed without merging**
