### PR TITLE
Update TPG version constraints to allow 4.0

### PR DESCRIPTION
**Pull request by nlamirault**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by thetimbecker** [comment]
Thank you @nlamirault for putting this together, I cannot use this module without this update. For this reason, [Terraform recommends using a `>=` for shared Terraform modules.](https://www.terraform.io/language/modules/develop/providers#provider-aliases-within-modules)

>If you are writing a shared Terraform module, constrain only the minimum required provider version using a `>=` constraint. This should specify the minimum version containing the features your module relies on, and thus allow a user of your module to potentially select a newer provider version if other features are needed by other parts of their overall configuration.

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR @nlamirault 
Could you pull in changes from https://github.com/terraform-google-modules/terraform-google-github-actions-runners/pull/44. In particular we use examples for testing modules and we want to make sure those pass. Unfortunately GKE runners are still blocked by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1129

**Comment by bharathkkb** [comment]
@thetimbecker Thanks for the suggestion, however we like to keep an upper constraint to validate that the module works with the new provider versions. This helps us catch issues that may have otherwise impacted our users and work with the provider teams to fix.

**Comment by simpsonw** [comment]
@nlamirault @bharathkkb Is there anything I can do to help move this PR along?  I noticed the GKE PR mentioned has been merged.  I'd like to use this for a project I'm working on, so if there's any way I can help, please let me know!

**Comment by nlamirault** [comment]
I don't have access to failed tests.

**Review by bharathkkb — COMMENTED** [review]
@nlamirault looks like some lint tests are failing. You can see the details here https://github.com/terraform-google-modules/terraform-google-github-actions-runners/pull/50#issuecomment-1016302483. You can also run it locally using `make docker_test_lint`.

**Comment by nlamirault** [comment]
Thanks @bharathkkb . I will check that.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
